replicaCount: 1
appName: app-to-render
serviceName: service-to-expose-json
image:
  repository: docker.io/anishihsag/flask-application
  tag: image-to-expose-json
  containerPort: 5002
service:
  type: ClusterIP
  port: 80
  targetPort: 5002

